/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rental_LazyPeople;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author mamaf
 */
public class PelangganLogin extends javax.swing.JFrame {
    private PreparedStatement stat;
    private ResultSet rs;
    Koneksi k = new Koneksi();
    
    public PelangganLogin() {
        initComponents();
        k.connect();
    }
    
    class Pelanggan{
        String usn_pelanggan, pw_pelanggan;
        
        public Pelanggan(){
            this.usn_pelanggan = isiusername.getText();
            this.pw_pelanggan = isipassword.getText();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isiusername = new javax.swing.JTextField();
        isipassword = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        btnout = new javax.swing.JButton();
        btnlihat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        isiusername.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        isiusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiusernameActionPerformed(evt);
            }
        });
        getContentPane().add(isiusername);
        isiusername.setBounds(400, 430, 380, 70);

        isipassword.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(isipassword);
        isipassword.setBounds(400, 530, 380, 70);

        btnlogin.setBorderPainted(false);
        btnlogin.setContentAreaFilled(false);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(300, 630, 370, 70);

        btnout.setText("<");
        btnout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnout);
        btnout.setBounds(0, 0, 80, 50);

        btnlihat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/png-transparent-computer-icons-button-encapsulated-postscript-viewing-text-logo-black.png"))); // NOI18N
        btnlihat.setText("jButton1");
        btnlihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlihatActionPerformed(evt);
            }
        });
        getContentPane().add(btnlihat);
        btnlihat.setBounds(810, 530, 80, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Login Username.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 1000);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        PelangganLogin.Pelanggan u = new PelangganLogin.Pelanggan();
        try {
            this.stat = k.getCon().prepareStatement("SELECT * FROM users WHERE usn_pelanggan = '" + u.usn_pelanggan + "' AND pw_pelanggan = '" + u.pw_pelanggan + "'");
            this.rs = this.stat.executeQuery();
            
            if(!rs.next()){
                JOptionPane.showMessageDialog(null, "Daftar dulu!");
            } else {
                new HomePelanggan().setVisible(true);
                this.setVisible(false);
        }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoutActionPerformed
        // TODO add your handling code here:
        new PilihPeran().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnoutActionPerformed

    private void isiusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiusernameActionPerformed

    private void btnlihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlihatActionPerformed
        // TODO add your handling code here:
        if (isipassword.echoCharIsSet()) {
            isipassword.setEchoChar((char)0);
        } else {
            isipassword.setEchoChar('*');
        }
    }//GEN-LAST:event_btnlihatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelangganLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelangganLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelangganLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelangganLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PelangganLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlihat;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnout;
    private javax.swing.JPasswordField isipassword;
    private javax.swing.JTextField isiusername;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
