/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rental_LazyPeople;

/**
 *
 * @author mamaf
 */
public class PilihPeran extends javax.swing.JFrame {

    /**
     * Creates new form PilihPeran
     */
    public PilihPeran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnloginpelanggan = new javax.swing.JButton();
        btnloginadmin = new javax.swing.JButton();
        btnout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);
        getContentPane().setLayout(null);

        btnloginpelanggan.setBorderPainted(false);
        btnloginpelanggan.setContentAreaFilled(false);
        btnloginpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginpelangganActionPerformed(evt);
            }
        });
        getContentPane().add(btnloginpelanggan);
        btnloginpelanggan.setBounds(300, 460, 370, 70);

        btnloginadmin.setBorderPainted(false);
        btnloginadmin.setContentAreaFilled(false);
        btnloginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginadminActionPerformed(evt);
            }
        });
        getContentPane().add(btnloginadmin);
        btnloginadmin.setBounds(290, 570, 390, 70);

        btnout.setText("<");
        btnout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnout);
        btnout.setBounds(0, 0, 80, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Pilih Peran.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 1000);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginpelangganActionPerformed
        // TODO add your handling code here:
        new PelangganLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnloginpelangganActionPerformed

    private void btnloginadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginadminActionPerformed
        // TODO add your handling code here:
        new Rental_LazyPeople.AdminLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnloginadminActionPerformed

    private void btnoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoutActionPerformed
        // TODO add your handling code here:
        new FrontGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihPeran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihPeran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihPeran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihPeran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihPeran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnloginadmin;
    private javax.swing.JButton btnloginpelanggan;
    private javax.swing.JButton btnout;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
