/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rental_LazyPeople;

/**
 *
 * @author mamaf
 */
public class RiwayatPesananPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public RiwayatPesananPelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnhomepage = new javax.swing.JButton();
        btnpemesanan = new javax.swing.JButton();
        btnkeranjang = new javax.swing.JButton();
        btnobjekwisata = new javax.swing.JButton();
        btnpeta = new javax.swing.JButton();
        btnriwayat = new javax.swing.JButton();
        btntentang = new javax.swing.JButton();
        btnout = new javax.swing.JButton();
        isikodepesanan = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableriwayat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 370));
        getContentPane().setLayout(null);

        btnhomepage.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnhomepage.setBorderPainted(false);
        btnhomepage.setContentAreaFilled(false);
        getContentPane().add(btnhomepage);
        btnhomepage.setBounds(40, 180, 160, 40);

        btnpemesanan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnpemesanan.setBorderPainted(false);
        btnpemesanan.setContentAreaFilled(false);
        getContentPane().add(btnpemesanan);
        btnpemesanan.setBounds(40, 240, 160, 40);

        btnkeranjang.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnkeranjang.setBorderPainted(false);
        btnkeranjang.setContentAreaFilled(false);
        btnkeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeranjangActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeranjang);
        btnkeranjang.setBounds(40, 310, 160, 40);

        btnobjekwisata.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnobjekwisata.setBorderPainted(false);
        btnobjekwisata.setContentAreaFilled(false);
        getContentPane().add(btnobjekwisata);
        btnobjekwisata.setBounds(40, 370, 160, 40);

        btnpeta.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnpeta.setBorderPainted(false);
        btnpeta.setContentAreaFilled(false);
        getContentPane().add(btnpeta);
        btnpeta.setBounds(40, 430, 160, 50);

        btnriwayat.setBackground(new java.awt.Color(255, 255, 255));
        btnriwayat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnriwayat.setBorderPainted(false);
        btnriwayat.setContentAreaFilled(false);
        btnriwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnriwayat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnriwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnriwayatActionPerformed(evt);
            }
        });
        getContentPane().add(btnriwayat);
        btnriwayat.setBounds(40, 490, 160, 60);

        btntentang.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btntentang.setBorderPainted(false);
        btntentang.setContentAreaFilled(false);
        getContentPane().add(btntentang);
        btntentang.setBounds(30, 870, 160, 40);

        btnout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnout.setBorderPainted(false);
        btnout.setContentAreaFilled(false);
        getContentPane().add(btnout);
        btnout.setBounds(30, 920, 160, 40);
        getContentPane().add(isikodepesanan);
        isikodepesanan.setBounds(260, 180, 550, 80);

        btncari.setBorderPainted(false);
        btncari.setContentAreaFilled(false);
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari);
        btncari.setBounds(810, 180, 130, 80);

        tableriwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "No.HP", "Tujuan", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableriwayat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 270, 680, 660);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Riwayat.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 1000);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnkeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeranjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeranjangActionPerformed

    private void btnriwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnriwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnriwayatActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesananPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesananPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesananPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesananPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatPesananPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhomepage;
    private javax.swing.JButton btnkeranjang;
    private javax.swing.JButton btnobjekwisata;
    private javax.swing.JButton btnout;
    private javax.swing.JButton btnpemesanan;
    private javax.swing.JButton btnpeta;
    private javax.swing.JButton btnriwayat;
    private javax.swing.JButton btntentang;
    private javax.swing.JTextField isikodepesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableriwayat;
    // End of variables declaration//GEN-END:variables
}
