/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rental_LazyPeople;

/**
 *
 * @author mamaf
 */
public class HomePelanggan extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomePelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnpesan = new javax.swing.JButton();
        btnobjek = new javax.swing.JButton();
        btnpeta = new javax.swing.JButton();
        btnriwayat = new javax.swing.JButton();
        lbljelawat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 370));
        getContentPane().setLayout(null);

        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });
        getContentPane().add(btnpesan);
        btnpesan.setBounds(60, 110, 140, 60);

        btnobjek.setText("Objek Wisata");
        getContentPane().add(btnobjek);
        btnobjek.setBounds(240, 110, 140, 60);

        btnpeta.setText("Peta Kota");
        btnpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpetaActionPerformed(evt);
            }
        });
        getContentPane().add(btnpeta);
        btnpeta.setBounds(420, 110, 140, 60);

        btnriwayat.setText("Riwayat Transaksi");
        btnriwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnriwayatActionPerformed(evt);
            }
        });
        getContentPane().add(btnriwayat);
        btnriwayat.setBounds(590, 110, 140, 60);

        lbljelawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/monumen-ikan-jelawat.png"))); // NOI18N
        lbljelawat.setText("jLabel1");
        getContentPane().add(lbljelawat);
        lbljelawat.setBounds(60, 180, 200, 100);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        jLabel1.setText("Patung atau Tugu Jelawat ini adalah Tugu yang berbentuk ikan ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 180, 450, 20);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        jLabel2.setText("yang menjadi ciri khas daerah sungai Mentaya ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 200, 330, 24);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/lovepik-summer-fresh-background-image_401540304.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 800, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpetaActionPerformed

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        PesanPelanggan psnplg = new PesanPelanggan();
        psnplg.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnpesanActionPerformed

    private void btnriwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnriwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnriwayatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnobjek;
    private javax.swing.JButton btnpesan;
    private javax.swing.JButton btnpeta;
    private javax.swing.JButton btnriwayat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbljelawat;
    // End of variables declaration//GEN-END:variables
}
